version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_bd
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - leon_data:/var/lib/mysql

volumes:
  leon_data: