server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: trabalho-banco
  datasource:
    url: jdbc:mysql://localhost:3306/Plataforma?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update